#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP1 -d I II III IV
bspc monitor eDP1 -d V VI
bspc wm -O DP1 eDP1

bspc config -m DP1 top_padding        20
bspc config -m eDP1 top_padding        0
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width       2
bspc config window_gap         10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false

bspc rule -a firefox:Places state=floating
bspc rule -a Screenkey manage=off
#bspc rule -a jetbrains-idea state=floating
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Gpick state=floating center=true
bspc rule -a Arandr state=floating center=true
bspc rule -a Gucharmap state=floating center=true

# Border
#bspc config focused_border_color        "#5E81AC"
bspc config focused_border_color        "#7B9CBD"
bspc config normal_border_color         "#2E3440"
bspc config active_border_color         "#073642"

#
# Autostart
#

# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/

# Picom
picom -b &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Keyboard
xset r rate 200 60

# Clipboard
pgrep -x xfce4-clipman > /dev/null || xfce4-clipman &
